[build]
  publish = "."
  command = "echo 'window.HALALDETECT_CONFIG = { apiKey: \"'$OPENAI_API_KEY'\" };' > config.js"
  environment = { SECRETS_SCAN_ENABLED = "false" }

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"